title: Note About Front End Development, Vue, React, Java Spring, Maven Etc.
author: libai8723
email: libai8723@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Finally find a place cool enough to host a blog
# social links
twitter_username: libai8723
github_username:  libai8723

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-hacker
