title: Note About Front End Development Big Nerd Book
author: libai8723
email: libai8723@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Finally find a place cool enough to host a blog
  This blog is about the learning note about front end development
# social links
twitter_username: libai8723
github_username:  libai8723

show_excerpts: true # set to false to remove excerpts on the homepage

theme: Hacker